### ISSUE TITLE
Several servers unreachable

### ISSUE THREAD

**Issue by lanyusea** [zackw/active-geolocator#3]
68.232.39.54:80: Error: connection timeout
208.80.155.69:80: Error: connection timeout
193.176.144.165:80: Error: connection timeout
199.10.66.231:80: Error: connection timeout
199.115.158.230:80: Error: connection timeout
197.80.75.4:80: Error: connection timeout
200.160.6.35:80: Error: connection timeout
193.188.128.54:80: Error: connection timeout
65.22.12.230:80: Error: connection timeout
87.238.48.242:80: Error: connection timeout
94.186.178.253:80: Error: connection timeout
77.95.70.141:80: Error: connection timeout
193.170.114.240:80: Error: connection timeout
192.248.1.187:80: Error: connection timeout
197.80.75.4:80: Error: connection timeout
200.10.230.196:80: Error: connection timeout
199.115.158.230:80: Error: connection timeout
77.95.70.141:80: Error: connection timeout
193.176.144.165:80: Error: connection timeout
87.238.48.242:80: Error: connection timeout
193.188.128.54:80: Error: connection timeout
199.10.66.231:80: Error: connection timeout
208.80.155.69:80: Error: connection timeout
65.22.12.230:80: Error: connection timeout
200.160.6.35:80: Error: connection timeout
193.170.114.240:80: Error: connection timeout
94.186.178.253:80: Error: connection timeout
194.160.223.106:80: Error: connection timeout
199.115.158.230:80: Error: connection timeout
193.188.128.54:80: Error: connection timeout
77.95.70.141:80: Error: connection timeout
199.10.66.231:80: Error: connection timeout
197.80.75.4:80: Error: connection timeout
192.248.1.187:80: Error: connection timeout
65.22.12.230:80: Error: connection timeout
geoip lookup failure: TypeError: Failed to fetch
TypeError: Failed to fetch
193.176.144.165:80: Error: connection timeout
200.160.6.35:80: Error: connection timeout
193.170.114.240:80: Error: connection timeout
87.238.48.242:80: Error: connection timeout
208.80.155.69:80: Error: connection timeout
199.10.66.231:80: Error: connection timeout
77.95.70.141:80: Error: connection timeout
65.22.12.230:80: Error: connection timeout
94.186.178.253:80: Error: connection timeout
208.80.155.69:80: Error: connection timeout
193.176.144.165:80: Error: connection timeout
197.80.75.4:80: Error: connection timeout
87.238.48.242:80: Error: connection timeout
193.188.128.54:80: Error: connection timeout
192.248.1.187:80: Error: connection timeout
200.160.6.35:80: Error: connection timeout
193.170.114.240:80: Error: connection timeout
199.115.158.230:80: Error: connection timeout
193.188.128.54:80: Error: connection timeout
208.80.155.69:80: Error: connection timeout
200.160.6.35:80: Error: connection timeout
197.80.75.4:80: Error: connection timeout
77.95.70.141:80: Error: connection timeout
199.10.66.231:80: Error: connection timeout
94.186.178.253:80: Error: connection timeout
192.248.1.187:80: Error: connection timeout
65.22.12.230:80: Error: connection timeout
193.170.114.240:80: Error: connection timeout
87.238.48.242:80: Error: connection timeout
193.176.144.165:80: Error: connection timeout
94.242.1.50:80: Error: connection timeout

---

The idea is quite attractive while the result may be not too exciting.

It locates me in a circle with 300km radius. While the browser, Chrome, locates me in the correct street but one block shifted.

**Comment by zackw** [comment]
Thank you for the heads-up, but this is normal. There's always a few servers that are down.

300km radius is about as good as it gets for this algorithm when run inside a browser, but that's often good enough to finger a _country_ or small group of countries, which is what I really care about.
