### ISSUE TITLE
Link seems to be broken

### ISSUE THREAD

**Issue by reethikar** [zackw/active-geolocator#5]
Looking up research.owlfolio.org:443...ok
Retrieving continent-level landmarks...
https://research.owlfolio.org/active-geo/api/1/continent-marks:
   HTTP Error 404: Not Found

This is what I got when I tried to run the probe command

**Comment by reethikar** [comment]
Config.log below:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by probe-core configure 1.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = Reethikas-MacBook-Pro.local
uname -m = x86_64
uname -r = 18.2.0
uname -s = Darwin
uname -v = Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Kernel configured for up to 8 processors.
4 processors are physically available.
8 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7
Primary memory available: 8.00 gigabytes
Default processor set: 344 tasks, 1965 threads, 8 processors
Load average: 1.53, Mach factor: 6.46
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /Users/reethika/.rbenv/shims
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin
PATH: /Library/TeX/texbin
PATH: /usr/local/go/bin
PATH: /Applications/Wireshark.app/Contents/MacOS


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1952: checking for gcc
configure:1968: found /usr/bin/gcc
configure:1979: result: gcc
configure:2208: checking for C compiler version
configure:2217: gcc --version >&5
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
configure:2228: $? = 0
configure:2217: gcc -v >&5
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
configure:2228: $? = 0
configure:2217: gcc -V >&5
clang: error: argument to '-V' is missing (expected 1 value)
clang: error: no input files
configure:2228: $? = 1
configure:2217: gcc -qversion >&5
clang: error: unknown argument: '-qversion'
clang: error: no input files
configure:2228: $? = 1
configure:2248: checking whether the C compiler works
configure:2270: gcc    conftest.c  >&5
configure:2274: $? = 0
configure:2322: result: yes
configure:2325: checking for C compiler default output file name
configure:2327: result: a.out
configure:2333: checking for suffix of executables
configure:2340: gcc -o conftest    conftest.c  >&5
configure:2344: $? = 0
configure:2366: result: 
configure:2388: checking whether we are cross compiling
configure:2396: gcc -o conftest    conftest.c  >&5
configure:2400: $? = 0
configure:2407: ./conftest
configure:2411: $? = 0
configure:2426: result: no
configure:2431: checking for suffix of object files
configure:2453: gcc -c   conftest.c >&5
configure:2457: $? = 0
configure:2478: result: o
configure:2482: checking whether we are using the GNU C compiler
configure:2501: gcc -c   conftest.c >&5
configure:2501: $? = 0
configure:2510: result: yes
configure:2519: checking whether gcc accepts -g
configure:2539: gcc -c -g  conftest.c >&5
configure:2539: $? = 0
configure:2580: result: yes
configure:2597: checking for gcc option to accept ISO C11
configure:2801: gcc  -c -g -O2  conftest.c >&5
configure:2801: $? = 0
configure:2814: result: none needed
configure:3119: checking for minix/config.h
configure:3119: gcc -c -g -O2  conftest.c >&5
conftest.c:10:10: fatal error: 'minix/config.h' file not found
#include <minix/config.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
configure:3119: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "probe-core"
| #define PACKAGE_TARNAME "probe-core"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "probe-core 1.0"
| #define PACKAGE_BUGREPORT "https://github.com/zackw/active-geolocator/issues/new"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| #include <minix/config.h>
configure:3119: result: no
configure:3139: checking whether it is safe to define __EXTENSIONS__
configure:3157: gcc -c -g -O2  conftest.c >&5
configure:3157: $? = 0
configure:3164: result: yes
configure:3189: checking for special C compiler options needed for large files
configure:3234: result: no
configure:3240: checking for _FILE_OFFSET_BITS value needed for large files
configure:3265: gcc -c -g -O2  conftest.c >&5
configure:3265: $? = 0
configure:3297: result: no
configure:3388: checking whether C compiler accepts -Werror=unknown-warning-option
configure:3407: gcc -c -g -O2  -Werror=unknown-warning-option  conftest.c >&5
configure:3407: $? = 0
configure:3415: result: yes
configure:3437: checking whether C compiler accepts -Wall
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wall  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3492: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3495: $? = 0
configure:3437: checking whether C compiler accepts -Wextra
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wextra  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3481: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3484: $? = 0
configure:3437: checking whether C compiler accepts -Wstrict-prototypes
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wstrict-prototypes  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3481: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3484: $? = 0
configure:3437: checking whether C compiler accepts -Wwrite-strings
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wwrite-strings  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3481: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3484: $? = 0
configure:3437: checking whether C compiler accepts -Wformat=2
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wformat=2  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3481: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3484: $? = 0
configure:3437: checking whether C compiler accepts -Wpedantic
configure:3456: gcc -c -g -O2 -Werror=unknown-warning-option -Wpedantic  conftest.c >&5
configure:3456: $? = 0
configure:3465: result: yes
configure:3481: : WARN_CFLAGS="$WARN_CFLAGS"
configure:3484: $? = 0
configure:3510: checking for _Static_assert
configure:3528: gcc -c -g -O2  conftest.c >&5
configure:3528: $? = 0
configure:3543: gcc -c -g -O2  conftest.c >&5
conftest.c:20:7: error: static_assert failed "this assertion should fail"
      _Static_assert(sizeof(int) < 1, "this assertion should fail");
      ^              ~~~~~~~~~~~~~~~
1 error generated.
configure:3543: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "probe-core"
| #define PACKAGE_TARNAME "probe-core"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "probe-core 1.0"
| #define PACKAGE_BUGREPORT "https://github.com/zackw/active-geolocator/issues/new"
| #define PACKAGE_URL ""
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define _DARWIN_C_SOURCE 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|       _Static_assert(sizeof(int) < 1, "this assertion should fail");
| 
|   ;
|   return 0;
| }
configure:3559: result: yes
configure:3569: checking for library containing lrint
configure:3600: gcc -o conftest -g -O2   conftest.c  >&5
conftest.c:23:6: warning: incompatible redeclaration of library function 'lrint' [-Wincompatible-library-redeclaration]
char lrint ();
     ^
conftest.c:23:6: note: 'lrint' is a builtin with type 'long (double)'
1 warning generated.
configure:3600: $? = 0
configure:3617: result: none required
configure:3631: checking for library containing clock_gettime
configure:3662: gcc -o conftest -g -O2   conftest.c  >&5
configure:3662: $? = 0
configure:3679: result: none required
configure:3693: checking for mach_absolute_time
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
configure:3693: $? = 0
configure:3693: result: yes
configure:3693: checking for gettimeofday
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
configure:3693: $? = 0
configure:3693: result: yes
configure:3693: checking for ppoll
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
Undefined symbols for architecture x86_64:
  "_ppoll", referenced from:
      _main in conftest-22edde.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3693: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "probe-core"
| #define PACKAGE_TARNAME "probe-core"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "probe-core 1.0"
| #define PACKAGE_BUGREPORT "https://github.com/zackw/active-geolocator/issues/new"
| #define PACKAGE_URL ""
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define _DARWIN_C_SOURCE 1
| #define HAVE__STATIC_ASSERT 1
| #define HAVE_CLOCK_GETTIME 1
| #define HAVE_MACH_ABSOLUTE_TIME 1
| #define HAVE_GETTIMEOFDAY 1
| /* end confdefs.h.  */
| /* Define ppoll to an innocuous variant, in case <limits.h> declares ppoll.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define ppoll innocuous_ppoll
| 
| /* System header to define __stub macros and hopefully few prototypes,
|     which can conflict with char ppoll (); below.
|     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
|     <limits.h> exists even on freestanding compilers.  */
| 
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 
| #undef ppoll
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char ppoll ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_ppoll || defined __stub___ppoll
| choke me
| #endif
| 
| int
| main ()
| {
| return ppoll ();
|   ;
|   return 0;
| }
configure:3693: result: no
configure:3693: checking for poll
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
configure:3693: $? = 0
configure:3693: result: yes
configure:3693: checking for mmap
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
configure:3693: $? = 0
configure:3693: result: yes
configure:3693: checking for closefrom
configure:3693: gcc -o conftest -g -O2   conftest.c  >&5
Undefined symbols for architecture x86_64:
  "_closefrom", referenced from:
      _main in conftest-ab59dc.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
configure:3693: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "probe-core"
| #define PACKAGE_TARNAME "probe-core"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "probe-core 1.0"
| #define PACKAGE_BUGREPORT "https://github.com/zackw/active-geolocator/issues/new"
| #define PACKAGE_URL ""
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define _DARWIN_C_SOURCE 1
| #define HAVE__STATIC_ASSERT 1
| #define HAVE_CLOCK_GETTIME 1
| #define HAVE_MACH_ABSOLUTE_TIME 1
| #define HAVE_GETTIMEOFDAY 1
| #define HAVE_POLL 1
| #define HAVE_MMAP 1
| /* end confdefs.h.  */
| /* Define closefrom to an innocuous variant, in case <limits.h> declares closefrom.
|    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
| #define closefrom innocuous_closefrom
| 
| /* System header to define __stub macros and hopefully few prototypes,
|     which can conflict with char closefrom (); below.
|     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
|     <limits.h> exists even on freestanding compilers.  */
| 
| #ifdef __STDC__
| # include <limits.h>
| #else
| # include <assert.h>
| #endif
| 
| #undef closefrom
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char closefrom ();
| /* The GNU C library defines this for functions which it implements
|     to always fail with ENOSYS.  Some functions are actually named
|     something starting with __ and the normal name is an alias.  */
| #if defined __stub_closefrom || defined __stub___closefrom
| choke me
| #endif
| 
| int
| main ()
| {
| return closefrom ();
|   ;
|   return 0;
| }
configure:3693: result: no
configure:3842: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by probe-core config.status 1.0, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on Reethikas-MacBook-Pro.local

config.status:798: creating Makefile
config.status:798: creating config.h

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_c__Static_assert=yes
ac_cv_c_compiler_gnu=yes
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_func_closefrom=no
ac_cv_func_gettimeofday=yes
ac_cv_func_mach_absolute_time=yes
ac_cv_func_mmap=yes
ac_cv_func_poll=yes
ac_cv_func_ppoll=no
ac_cv_header_minix_config_h=no
ac_cv_objext=o
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_cc_c11=
ac_cv_prog_cc_g=yes
ac_cv_prog_cc_stdc=
ac_cv_safe_to_define___extensions__=yes
ac_cv_search_clock_gettime='none required'
ac_cv_search_lrint='none required'
ac_cv_sys_file_offset_bits=no
ac_cv_sys_largefile_CC=no
ax_cv_check_cflags__Wall=yes
ax_cv_check_cflags__Wextra=yes
ax_cv_check_cflags__Wformat_2=yes
ax_cv_check_cflags__Wpedantic=yes
ax_cv_check_cflags__Wstrict_prototypes=yes
ax_cv_check_cflags__Wwrite_strings=yes
ax_cv_check_cflags___Werror_unknown_warning_option=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

CC='gcc'
CFLAGS='-g -O2'
CPPFLAGS=''
DEFS='-DHAVE_CONFIG_H'
ECHO_C='\c'
ECHO_N=''
ECHO_T=''
EXEEXT=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
OBJEXT='o'
PACKAGE_BUGREPORT='https://github.com/zackw/active-geolocator/issues/new'
PACKAGE_NAME='probe-core'
PACKAGE_STRING='probe-core 1.0'
PACKAGE_TARNAME='probe-core'
PACKAGE_URL=''
PACKAGE_VERSION='1.0'
PATH_SEPARATOR=':'
SHELL='/bin/sh'
WARN_CFLAGS='-Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wformat=2 -Wpedantic'
ac_ct_CC='gcc'
bindir='${exec_prefix}/bin'
build_alias=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host_alias=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##
## confdefs.h. ##
## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "probe-core"
#define PACKAGE_TARNAME "probe-core"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "probe-core 1.0"
#define PACKAGE_BUGREPORT "https://github.com/zackw/active-geolocator/issues/new"
#define PACKAGE_URL ""
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _GNU_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define _TANDEM_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define HAVE__STATIC_ASSERT 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_MACH_ABSOLUTE_TIME 1
#define HAVE_GETTIMEOFDAY 1
#define HAVE_POLL 1
#define HAVE_MMAP 1

configure: exit 0

**Comment by zackw** [comment]
This is because I took the server down after I was done collecting data myself.  I would like to recommend that you set up a server yourself, but it isn't exactly simple.  Or documented.  I'd have to reconstruct the procedure if I wanted to do it myself. :-/

What is your larger goal here?  Are you just experimenting with the code, or?

**Comment by reethikar** [comment]
Ah that's what I guessed. I was just experimenting with the code, that's alright! Thanks!
